### ISSUE TITLE
Extraneous Files ought to be deleted

### ISSUE THREAD

**Issue by rizend** [rmendez23/STEAM-Team-ROV#4]
All of the extraneous files should be deleted leaving only files we actually should focus on.  I think the files we want to keep are client_pi1.py, server_pi2.py, README.md, PyGameProcessing.py, and possibly joybuttons.py.

**Comment by rmendez23** [comment]
Agreed. Problem is there is one file that is a backup of an important file on the raspberry pi. Not sure where to put it. I think it is the `interfaces` one

**Comment by rizend** [comment]
This is dealt with in #7

**Comment by rizend** [comment]
Now that pull request #7 has been merged, this issue is fixed.
